# Generated by Django 3.2.6 on 2021-08-22 21:10

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, help_text='The post content', verbose_name='body'),
        ),
    ]
