# Generated by Django 2.2.5 on 2019-09-24 07:43

from django.conf import settings
from django.db import migrations, models
import research.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='Slug for URL.', max_length=128, unique=True, verbose_name='slug')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Date of last modification', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=False, help_text='Is active', verbose_name='active')),
                ('activation_date', models.DateTimeField(blank=True, help_text='Date of activation', null=True, verbose_name='activated at')),
                ('papertype', models.CharField(choices=[('Article', 'Published'), ('Unpublished', 'Unpublished'), ('Techreport', 'Working paper'), ('Inproceedings', 'Conference article'), ('Misc', 'Miscellaneous')], default='Article', max_length=64, verbose_name='papertype')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('institution', models.CharField(blank=True, max_length=256, verbose_name='institution')),
                ('journal', models.CharField(blank=True, max_length=256, verbose_name='journal')),
                ('pages', models.CharField(blank=True, max_length=32, verbose_name='pages')),
                ('volume', models.CharField(blank=True, max_length=32, verbose_name='volume')),
                ('number', models.CharField(blank=True, max_length=16, verbose_name='number')),
                ('link', models.URLField(blank=True, verbose_name='link')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='note')),
                ('pdf', models.FileField(blank=True, upload_to=research.utils.rename_pdf, validators=[research.utils.validate_pdf_extension], verbose_name='PDF')),
                ('mime', models.CharField(blank=True, editable=False, max_length=64, verbose_name='mime')),
                ('downloaded', models.IntegerField(default=0, editable=False, verbose_name='downloaded')),
                ('last_downloaded', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last downloaded')),
                ('authors', models.ManyToManyField(related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
    ]
