# Generated by Django 2.2.5 on 2019-09-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20190924_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='project_link',
            field=models.URLField(blank=True, verbose_name='Link to project'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link to journal'),
        ),
    ]
