# Generated by Django 2.2.5 on 2020-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20190924_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='binder_link',
            field=models.URLField(blank=True, verbose_name='Link to binder'),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('Unpublished', 'Unpublished'), ('Published', 'Published'), ('Revise', 'Revise & resubmit ')], default='Unpublished', max_length=64, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='papertype',
            field=models.CharField(choices=[('Article', 'Published'), ('Unpublished', 'Unpublished'), ('Techreport', 'Working paper'), ('Inproceedings', 'Conference article'), ('Misc', 'Miscellaneous')], default='Unpublished', max_length=64, verbose_name='papertype'),
        ),
    ]
