# Generated by Django 2.2.5 on 2019-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='post',
            name='last_viewed',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last viewed', null=True),
        ),
    ]
