# Generated by Django 2.2 on 2019-04-29 10:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190428_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, help_text='The post content', verbose_name='body'),
        ),
    ]
