# Generated by Django 3.2.6 on 2021-08-13 20:56

from django.conf import settings
from django.db import migrations, models
import research.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Paper_keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, db_index=False, help_text='Slug for URL.', max_length=128, unique=True, verbose_name='slug')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Date of last modification', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=False, help_text='Is active', verbose_name='active')),
                ('activation_date', models.DateTimeField(blank=True, help_text='Date of activation', null=True, verbose_name='activated at')),
                ('papertype', models.CharField(choices=[('Article', 'Published'), ('Unpublished', 'Unpublished'), ('Techreport', 'Working paper'), ('Inproceedings', 'Conference article'), ('Misc', 'Miscellaneous')], default='Unpublished', max_length=64, verbose_name='papertype')),
                ('status', models.CharField(choices=[('Unpublished', 'Unpublished'), ('Published', 'Published'), ('Revise', 'Revise & resubmit')], default='Unpublished', max_length=64, verbose_name='status')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('institution', models.CharField(blank=True, max_length=256, verbose_name='institution')),
                ('project_link', models.URLField(blank=True, verbose_name='Link to project')),
                ('binder_link', models.URLField(blank=True, verbose_name='Link to binder')),
                ('journal', models.CharField(blank=True, max_length=256, verbose_name='journal')),
                ('pages', models.CharField(blank=True, max_length=32, verbose_name='pages')),
                ('volume', models.CharField(blank=True, max_length=32, verbose_name='volume')),
                ('number', models.CharField(blank=True, max_length=16, verbose_name='number')),
                ('link', models.URLField(blank=True, verbose_name='Link to journal')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='note')),
                ('pdf', models.FileField(blank=True, upload_to='', validators=[research.models.validate_pdf_extension], verbose_name='PDF')),
                ('mime', models.CharField(blank=True, editable=False, max_length=64, verbose_name='mime')),
                ('authors', models.ManyToManyField(related_name='papers', to=settings.AUTH_USER_MODEL)),
                ('keywords', tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=5, to='Research.Tagulous_Paper_keywords')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
    ]
