# Generated by Django 3.2.6 on 2021-08-30 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_alter_paper_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='version',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 30, 9, 53, 54, 790786, tzinfo=utc), help_text='Date of version', verbose_name='version date'),
            preserve_default=False,
        ),
    ]
