# Generated by Django 3.2.6 on 2021-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_paper_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='version',
            field=models.DateTimeField(blank=True, help_text='Date of version', null=True, verbose_name='version date'),
        ),
    ]
