# Generated by Django 3.2.13 on 2022-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_alter_paper_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('Unpublished', 'Unpublished'), ('Published', 'Published'), ('Revise', 'Revise & resubmit'), ('Forthcoming', 'Forthcoming')], default='Unpublished', max_length=64, verbose_name='status'),
        ),
    ]
